# ========================================================================================
# Body
# ========================================================================================

# 背景
background: https://www.dmoe.cc/random.php

# ========================================================================================
# Header
# ========================================================================================
# 搜索选择
search: 
  enable: true
  service: hexo # 选择搜索引擎：google（谷歌搜索）hexo（Hexo本地搜索）algolia（Algolia搜索）azure（微软Azure搜索）baidu（百度搜索）
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# 顶部菜单（PS：后面需要添加“/”才能保证pjax的正常运行！）
menu:
  - name: archive
    slug: fa-solid fa-box-archive
    url: /archives/
  - name: say
    slug: fa-solid fa-note-sticky
    url: /say/
  - name: friend
    slug: fa-solid fa-link
    url: /links/

# ========================================================================================
# Sidebar
# ========================================================================================

# 侧边栏
# 建议：about（关于）、links（社交链接，请在下面social配置）、categories（分类）、tagcloud（标签页）
# 可选：qweather（侧边天气）、music（侧边音乐播放器）
widgets:
  - about
  - links
  - categories
  - tagcloud
  - weather
  - music

# 侧边栏头像
avatar: /images/avatar.jpg

# 侧边栏社交链接
social:
- name: Github
  slug: fa-brands fa-github
  url: https://github.com/StarWEB890
- name: Bilibili
  slug: fa-brands fa-bilibili
	url: https://space.bilibili.com/479627766
- name: Email
  slug: fa-solid fa-envelope
	url: mailto:starinno@xsnetw.cf
- name: RSS
  slug: fa-solid fa-square-rss
	url: /atom.xml

# 侧边音乐播放器
# 使用APlayer+MetingJS
music:
  autoHide: true    # hide automaticaly
  server: netease   # require	music platform: netease, tencent, kugou, xiami, baidu
  type: playlist    #require song, playlist, album, search, artist
  id: 7515491376     # require	song id / playlist id / album id / search keyword
  fixed: true       # 开启吸底模式
  autoplay: false   # 是否自动播放
  theme: '#42b983'
  loop: 'all'       # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'   # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto'   # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7       # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true  # 列表默认折叠
  hideLrc: false     # 隐藏歌词

# ========================================================================================
# Footer
# ========================================================================================

# 末尾滚动一言
hitokoto: true

# 每个选项对应的color可选：write、blue、green、purple、orange、red、pink、yellow
color:
  moeicp:
  furryicp:
  icpbeian:
  gongan:
  tongji:
    pv:
    uv:
  powered:
  hosted:
  themesby:

# 末尾博客部署位置
hosted_by: 
  name: Vercel #部署在哪,例如Github Pages、Vercel、Coding等
  link: https://vercel.com/ #对应链接

# 萌ICP备案（不是真正的中国备案！）
# 申请请到：https://icp.gov.moe/join.php
# 然后把号码粘贴到code即可（PS:“萌ICP备”不用加上去！）
moeicp: 
  code: 

# 兽圈专属ICP备案系统（不是真正的中国备案！）（福瑞控狂喜 | doge）
# 申请请到：https://www.furgov.cn/
# 然后把号码粘贴到code即可（PS:“兽ICP备”不用加上去！） 
furryicp: 
  code: 

# ICP备案（真正的中国备案）
icpbeian: 
  name: #备案信息

# 公安网备案
gongan:
  enable: 
  code:  #备案号
  type:  #显示备案信息

# 不蒜子统计
# https://busuanzi.ibruce.info
busuanzi: false

# Visit-Stat统计
# https://github.com/Lete114/Visit-Stat
# 服务端搭建教程：https://www.xsnetw.cf/posts/54175/
# 把服务端地址复制到下面的“serverURL”就行（后面千万不要“/”!）
visit_stat:
  enable: false
  serverURL: 

# 自定义末尾右侧栏
footer_right: "<a href=\"https://travellings.cn\" target=\"_blank\" class=\"menu-item-travelling\" rel=\"noopener\" title=\"开往-友链接力\">
    <img src=\"https://travellings.cn/assets/logo.gif\" alt=\"开往-友链接力\" width=\"120\">
</a>"

# ========================================================================================
# 特效
# ========================================================================================

body:
  canvas: # Canvas-Nest
    enable: false
    color: rgb(85,85,85)

# 毛玻璃效果（可能会造成卡顿！）
glass: false

headereffect:
  titlelight: true # 头部标题发光特效
  menuhover: true # 头部菜单hover特效

readmore:
  light: true # “阅读更多”hover发光特效
  rotate: true # “阅读更多”边框旋转特效

# ========================================================================================
# 友情链接
# ========================================================================================

# 友情链接配置：
# 编辑博客根目录下的“_config.yml”，设置“title”（博客名）、“description”（博客描述）、“url”（博客网址）
# 再编辑linkavatar（PS：必须是https开头！）
linkavatar: https://cdn.xsnetw.cf/SinGo/images/avatar.jpg
dalao:
  - name: 名称（如SinGO博客）
    link: 链接（如：https://www.xsnetw.cf）
    avatar: 头像链接（如 https://www.xsnetw.cf/images/avatar.jpg）
    info: 描述：（如：害怕孤独，却享受孤独）
    color: rgb(0,139,139)

xiaohuoban:
  - name: 名称（如SinGO博客）
    link: 链接（如：https://www.xsnetw.cf）
    avatar: 头像链接（如 https://www.xsnetw.cf/images/avatar.jpg）
    info: 描述：（如：害怕孤独，却享受孤独）
    color: rgb(0,139,139)

#  - name: 名称（如SinGO博客）
#    link: 链接（如：https://www.xsnetw.cf）
#    avatar: 头像链接（如 https://www.xsnetw.cf/images/avatar.jpg）
#    info: 描述（如：害怕孤独，却享受孤独）
#    color: 颜色（示例：“rgb(0,139,139)”）

# ========================================================================================
# 附加功能
# ========================================================================================

# 评论功能
comment:
  enable: true # 开启评论功能
  type: waline # 选择评论：discuss | twikoo | gitalk | waline | giscus
  discuss: # Discuss设置：https://discuss.js.org
    server_url:  #评论服务端地址
    lang: cn #用于手动设定评论区语言，支持的语言列表 https://discuss.js.org/Quick-Start.html#lang
    ph: 有话想说？ #原名placeholder，评论框占位符，可自定义，默认值与lang有关系
  twikoo: # Twikoo设置：https://twikoo.js.org
    envId:  # 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
    region: # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
    lang: zh-CN #用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/js/utils/i18n/index.js
  gitalk: # Gitalk设置：https://github.com/gitalk/gitalk/blob/master/readme-cn.md
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.href
    distractionFreeMode: false
    # en | zh-CN | zh-TW
    language: navigator.language || navigator.userLanguage
    labels: ['Gitalk']
    perPage: 10
  giscus: # Giscus设置：https://giscus.app/zh-CN
    repo: ''
    repo_id: ''
    category: ''
    category_id: ''
    mapping: 'pathname'
    input_position: 'top'
    theme: 'light'
    lang: 'zh-CN'
  waline: # Waline设置：https://waline.js.org
    # 更多选项 https://waline.js.org/reference/component.html 按照yml格式继续填写即可
    serverURL: 
    login: force # disable（关闭登录功能） | enable（开启登录功能） | force（强制登录）
    meta: ['nick', 'mail', 'link'] #（login设置force时此项无效）评论者相关属性。可选值: 'nick', 'mail', 'link'
    requiredMeta: ['nick', 'mail'] #（login设置force时此项无效）设置必填项，默认匿名，可选值: [] 、 ['nick'] 、 ['nick', 'mail']
    lang: zh-CN
    emoji: [
    '//unpkg.com/@waline/emojis@1.0.1/weibo',
    'https://emoji.shojo.cn/bili/src/小黄脸',
    '//unpkg.com/@waline/emojis@1.0.1/bilibili',
    'https://emoji.shojo.cn/bili/src/枕边童话',
    'https://emoji.shojo.cn/bili/src/咩栗',
    'https://emoji.shojo.cn/bili/src/呜米',
    'https://emoji.shojo.cn/bili/src/进击的冰糖',
    'https://emoji.shojo.cn/bili/src/冰糖IO 蜕变·闪耀',
    'https://emoji.shojo.cn/bili/src/多多poi',
    'https://emoji.shojo.cn/bili/src/穆小泠',
    'https://emoji.shojo.cn/bili/src/早稻叽',
    ]

# Less
less:
  compress: true

# Pjax
pjax: true

# KaTex
katex: true

# Hexo说说
shuoshuo:
  enable: false
  type: kkapi # 选择一个说说：artitalk | kkapi | daodao
  artitalk: # https://artitalk.js.org/
    serverURL: 
    #LeanCloud中国版填绑定的API域名，如果你想使用Artitalk_SafeMode就填写“xxxx.workers.dev域名”
    appID:  #LeanCloud APPID（Artitalk_SafeMode可以滚键盘）
    appKey:  #LeanCloud APPKEY（Artitalk_SafeMode可以滚键盘）
  kkapi: # https://kkapi.js.org/
    serverURL:  # 部署kkapi地址（记住不是kkapi-open的地址！）
    author:  # 个人id
    loadimg: https://cdn.bobo.now.cc/gh/StarWEB890/TuChuang/images/load.6i582rbr59s0.gif #加载动画
    comment: waline # 使用评论，目前仅支持：waline、twikoo、discuss（请在上面设置评论）
  daodao_swiper: # 教程：https://blog.xsnetw.cf/posts/25517/
    jssrc: https://cdn.staticaly.com/gh/StarWEB890/daodao/main/daodao.js #请将StarWEB890改为你Github的名字，或者你自定义链接
    url:  #你的vercel部署地址
    fliter: "['img','iframe']"
    priority: 10
    enable: true
    enable_page: /
    layout:
      type: id
      name: recent-posts
      index: 0
    temple_html: '<div class="recent-post-item" style="height: auto;width: 100%"><div class="bbTimeList container" style="height: auto;width: 100%" id="bbTimeList"><i class="bber-gotobb fas fa-bullhorn" onclick="location=&#39;/daodao/&#39;" title="叨叨"></i><div class="swiper-container" id="bbtalk"><div class="swiper-wrapper" id="bber-talk" onclick="location=&#39;/daodao/&#39;"></div></div><i class="bber-gotobb fas fa-arrow-circle-right" onclick="location=&quot;/daodao/&quot;" title="查看全文"></i></div></div>'
    


# 在线聊天（类似在线客服）

#Chatra
chatra: 
  enable: false
  public_key:  #直接复制Public key到此就行

#Daovoice
daovoice: 
  enable: false
  app_id:  #直接复制app_id到此就行

# 动画效果（请在 https://animate.style/ 选择）
animate:
  index: animate__flipInX #首页、分类页、标签页效果
  archive: animate__bounceIn #归档页效果
  shuoshuo: animate__lightSpeedInRight #说说页面效果
  friend:
    link: animate__bounceInDown #友链页效果
    comment: animate__bounceInUp #友链页评论区效果
  post:
    postani: animate__fadeInDown #页面、文章效果
    commentani: animate__fadeInUp #评论区效果

# 版权信息
copyright:
    enable: true

# Live2D
live2d:
  enable: false
  api: https://live2d.bobo.now.cc/

# ========================================================================================
# CDN
# ========================================================================================
CDN:
  # 自定义SinGO主题css，建议不填（有镜像的可以填）
  css: 
  # 自定义SinGO主题js，建议不填（有镜像的可以填）
  js:
    jqueryfitvids: 
    app: 
    search: 

  #canvas
  canvasnest: https://cdn.bootcdn.net/ajax/libs/canvas-nest.js/2.0.4/canvas-nest.js

  # fontawesome
  fontawesome: https://cdn.bootcdn.net/ajax/libs/font-awesome/6.1.2/css/all.min.css

  # animate.css
  animate: https://cdn.bootcdn.net/ajax/libs/animate.css/4.1.1/animate.css

  # katex
  katex:
    css: https://cdn.bobo.now.cc/npm/katex/dist/katex.min.css
    js: https://cdn.bobo.now.cc/npm/katex/dist/katex.min.js
    rander: https://cdn.bobo.now.cc/npm/katex/dist/contrib/auto-render.min.js

  # 说说
  shuoshuo:
    artitalk: https://unpkg.com/artitalk
    kkapi:
      css: https://cdn1.tianli0.top/npm/ispeak/style.css
      js: https://cdn1.tianli0.top/npm/ispeak/ispeak.umd.js
      marked: https://cdn.staticfile.org/marked/2.0.0/marked.min.js
      highlight:
        css: https://cdn.staticfile.org/highlight.js/10.6.0/styles/atom-one-dark.min.css
        js: https://cdn.staticfile.org/highlight.js/10.6.0/highlight.min.js
    daodao:
      css: https://cdn.bobo.now.cc/gh/StarWEB890/TuChuang/npm/daodao/main.css
      swiper:
        css: https://cdn.bootcdn.net/ajax/libs/Swiper/8.3.2/swiper-bundle.min.css
        js: https://cdn.bootcdn.net/ajax/libs/Swiper/8.3.2/swiper-bundle.min.js

  #评论
  comment:
    twikoo: https://cdn.staticfile.org/twikoo/1.5.11/twikoo.all.min.js
    discuss: https://lib.baomitu.com/discuss/latest/dist/discuss.js
    giscus: https://giscus.app/client.js
    waline:
      css: https://unpkg.com/@waline/client@v2/dist/waline.css
      js: https://unpkg.com/@waline/client@v2/dist/waline.js
    gitalk:
      css: https://unpkg.com/gitalk@latest/dist/gitalk.css
      js: https://unpkg.com/gitalk@latest/dist/gitalk.min.js
      md5: https://priesttomb.github.io/js/md5.min.js
  
  # 音乐
  aplayer:
    css: https://unpkg.com/aplayer@1.10.1/dist/APlayer.min.css
    js: https://unpkg.com/aplayer@1.10.1/dist/APlayer.min.js
    metingjs: https://unpkg.com/meting/dist/Meting.min.js

  # Live2D（必须是绝对路径！）
  live2d: https://cdn.bobo.now.cc/gh/stevenjoezhang/live2d-widget@latest/