# ========================================================================================
# Header
# ========================================================================================
# 搜索选择
search: 
  enable: true
  service: hexo # 选择搜索引擎：google（谷歌搜索）hexo（Hexo本地搜索）algolia（Algolia搜索）azure（微软Azure搜索）baidu（百度搜索）
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# 顶部菜单（PS：后面需要添加斜杠才能保证pjax的正常运行！）
menu:
  - name: home
    slug: fa fa-home
    url: /
  - name: archive
    slug: fa fa-archive
    url: /archives/
  - name: friend
    slug: fa fa-external-link
    url: /links/
  - name: note
    slug: fa fa-sticky-note-o
    url: /note/

# ========================================================================================
# Sidebar
# ========================================================================================

# 侧边栏
# 建议：about（关于）、links（社交链接，请在下面social配置）、categories（分类）、tagcloud（标签页）
# 可选：qweather（侧边天气）、music（侧边音乐播放器）
widgets:
  - about
  - links
  - categories
  - tagcloud
  - qweather
  - music

# 侧边栏头像
avatar: /images/avatar.jpg

# 侧边栏社交链接
social:
- name: github
  slug: fa fa-github
  url: https://github.com/StarWEB890
- name: rss
  slug: fa fa-rss
	url: /atom.xml

# 侧边天气 KEY（在 https://widget.qweather.com/create-simple 这里创建一个，然后直接复制key到此，当然用我默认的也行，但可能随时失效）
weather: 42fbe0b777324e8e98785e69a3a69b87

# 侧边音乐播放器
# 使用APlayer+MetingJS
music:
  server: netease  #音乐平台：netease(网易云音乐)，tencent(QQ音乐)，kugou(酷狗音乐)
  type: playlist  #歌曲类型song，playlist，album，search，artist
  id: 7515491376 #（当然可以用我默认的）歌曲ID(song) /播放列表ID(playlist) /专辑ID(album) /搜索关键字(search) /歌手ID(artist)
  mini: false #迷你模式（注意：与吸底模式冲突）
  fixed: true #吸低模式（注意：与迷你模式冲突）
  autoplay: true #自动播放
  loop: all #播放器循环播放，值：“all”，one”，“none”
  order: random #播放器播放顺序，值：“list”，“random”
  preload: auto #默认就行
  listfolded: true #指示列表是否应该首先折叠

# ========================================================================================
# 友情链接
# ========================================================================================

# 友情链接配置：
# 编辑博客根目录下的“_config.yml”，设置“title”（博客名）、“description”（博客描述）、“url”（博客网址）
# 再编辑linkavatar（PS：必须是https开头！）
linkavatar: https://www.xsnetw.cf/images/avatar.jpg
links:
  - name: SinGO博客
    link: https://www.xsnetw.cf
    avatar: https://www.xsnetw.cf/images/avatar.jpg
    info: 害怕孤独，却享受孤独

#  - name: 名称（如SinGO博客）
#    link: 链接（如：https://www.xsnetw.cf）
#    avatar: 头像链接（如 https://www.xsnetw.cf/images/avatar.jpg）
#    info: 描述：（如：害怕孤独，却享受孤独）

# ========================================================================================
# 附加功能
# ========================================================================================

# 评论功能
comment:
  enable: true # 开启评论功能
  type: twikoo # discuss | twikoo | gitalk 
  # Gitalk设置：https://github.com/gitalk/gitalk/blob/master/readme-cn.md
  # Discuss设置：https://discuss.js.org
  # Twikoo设置：https://twikoo.js.org
  discuss:
    server_url: https://sin-go-discuss.vercel.app #评论服务端地址
    lang: cn #用于手动设定评论区语言，支持的语言列表 https://discuss.js.org/Quick-Start.html#lang
    ph: 有话想说？ #原名placeholder，评论框占位符，可自定义，默认值与lang有关系
  twikoo:
    envId: https://sin-go-twikoo.vercel.app/ # 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
    region: # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
    lang: zh-CN #用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/js/utils/i18n/index.js
  gitalk:
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.href
    distractionFreeMode: false
    # en | zh-CN | zh-TW
    language: navigator.language || navigator.userLanguage
    labels: ['Gitalk']
    perPage: 10

# 萌ICP备案（仅提供萌站长交流！不是真正的中国备案！）
# 申请请到：https://icp.gov.moe/join.php
# 然后把号码粘贴到“code”页面即可（PS:“萌ICP备”不用加上去！）
moeicp:
  enable: false
  code: 

# 不蒜子统计
# https://busuanzi.ibruce.info
busuanzi: true

# canvas
canvas: true

# Less
less:
  compress: true

# Pjax
pjax: true

# Artitalk（note页面需要Artitalk）
# （建议：https://artitalk.js.org/settings.html#artitalk-safemode）
# 开启之后，需要在你想添加的文章或者页面（title下面）加上：
# type: "artitalk"
# layout: "artitalk"
artitalk:
  enable: true
  serverURL: 
  #LeanCloud中国版填绑定的API域名，如果你想使用Artitalk_SafeMode就填写“xxxx.workers.dev域名”（但建议CloudFlare绑定域名）
  appID:  #LeanCloud APPID（Artitalk_SafeMode可以滚键盘）
  appKey:  #LeanCloud APPKEY（Artitalk_SafeMode可以滚键盘）


# 在线聊天（类似在线客服）

#Chatra
chatra: 
  enable: true
  public_key:  #直接复制Public key到此就行

#Daovoice
daovoice: 
  enable: false
  app_id:  #直接复制app_id到此就行

# ========================================================================================
# CDN
# ========================================================================================
fontawesome: https://unpkg.com/font-awesome@4.7.0/css/font-awesome.min.css