# ===========================================================================================
# Header
# ===========================================================================================

# 搜索功能
# Search
search: 
  enable: true
  service: hexo # 选择搜索引擎（Select search engine）：google、hexo、algolia、azure、baidu
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# 头部导航菜单
# navigation menu
#（PS：后面必须要加斜杠才能保证Pjax运行！）
menu:
  Home: /
  Archives: /archives/
  About: /about/

# ===========================================================================================
# Sidebar
# ===========================================================================================

# 侧边导航菜单
# widgets
# 可选：about（关于）、links（社交链接）、categories（分类）、tagcloud（标签云）、qweather（和风天气）
widgets:
  - about
  - links
  - categories
  - tagcloud
  - qweather

# 社交链接
# Social Links
social:
- name: Github
  slug: fa fa-github
  url: https://github.com/StarWEB890
- name: RSS订阅
  slug: fa fa-rss
	url: /atom.xml

# ===========================================================================================
# Additional functions （附加功能)（机翻）
# ===========================================================================================

# Less
less:
  compress: true

# pjax
pjax: true

# Comments
# 评论功能

# Waline评论
# https://waline.js.org
waline: 
  enable: false
  libUrl: https://unpkg.com/@waline/client@v1/dist/Waline.min.js # Waline JS CDN
  cssUrl: https://cdn.staticaly.com/gh/StarWEB890/TuChuang@master/waline.css # Waline CSS CDN（或自定义CSS）
  server_url: '' #评论服务端地址
  pageSize: 10 # 评论数量多少时显示分页 
  emoji: [
    '//unpkg.com/@waline/emojis@1.0.1/weibo',
    '//unpkg.com/@waline/emojis@1.0.1/bilibili',
    'https://emoji.shojo.cn/bili/src/枕边童话',
    'https://emoji.shojo.cn/bili/src/咩栗',
    'https://emoji.shojo.cn/bili/src/呜米',
    'https://emoji.shojo.cn/bili/src/多多poi',
    'https://emoji.shojo.cn/bili/src/穆小泠',
    'https://emoji.shojo.cn/bili/src/扶桑大红花',
    'https://emoji.shojo.cn/bili/src/进击的冰糖',
    'https://emoji.shojo.cn/bili/src/冰糖IO 蜕变·闪耀',
    'https://emoji.shojo.cn/bili/src/蕾尔娜Leona',
  ] # Waline 表情包
  login: force # 登录功能，可选：enable（开启登录功能）、disable（关闭登录功能）、force（强制登录）

## Twikoo
## https://twikoo.js.org/
discuss:
  enable: false # 是否启用 Twikoo 评论系统
  server_url:  #评论服务端地址
  lang: cn #用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/js/utils/i18n/index.js

## Twikoo
## https://twikoo.js.org/
twikoo:
  enable: false # 是否启用 Twikoo 评论系统
  envId:  # 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
  region: # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
  lang: zh-CN #用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/js/utils/i18n/index.js

## Gitalk
## https://gitalk.github.io/
## 网上有教程，可以的话按照教程来配置
gitalk:
  enable: false # 是否启用 gitalk 评论系统
  admin:  # 你的 GitHub 用户名
  owner:  # Github 仓库管理者用户名
  repo:  # GitHub 博客的仓库名称
  ClientID:  # 你的ClientID
  ClientSecret: # 你的Client Secret
  labels: #你的issue标签
  distractionFreeMode: true  #无干扰模式

## 萌ICP备案（仅提供萌站长交流！不是真正的中国备案！）
## 申请请到：https://icp.gov.moe/join.php
## 然后把号码粘贴到“code”页面即可（PS:“萌ICP备”不用加上去！）
moeicp:
  enable: false
  code: 

## 音乐播放器
## 使用APlayer+MetingJS
music:
  enable: true #开启音乐播放器
  server: netease  #音乐平台：netease(网易云音乐)，tencent(QQ音乐)，kugou(酷狗音乐)
  type: playlist  #歌曲类型song，playlist，album，search，artist
  id: 7515491376 #（当然可以用我默认的）歌曲ID(song) /播放列表ID(playlist) /专辑ID(album) /搜索关键字(search) /歌手ID(artist)
  fixed: true #吸低模式
  autoplay: true #自动播放
  loop: all #播放器循环播放，值：“all”，one”，“none”
  order: random #播放器播放顺序，值：“list”，“random”
  preload: auto #默认就行
  listfolded: true #指示列表是否应该首先折叠

## 不蒜子统计
## https://busuanzi.ibruce.info
busuanzi: true

## canvas
canvas: true

# ===========================================================================================
# CDN
# ===========================================================================================
# fontawesome cdn
fontawesome: https://unpkg.com/font-awesome@4.7.0/css/font-awesome.min.css