# ========================================================================================
# Header
# ========================================================================================
# 搜索选择
search: 
  enable: true
  service: hexo # 选择搜索引擎：google（谷歌搜索）hexo（Hexo本地搜索）algolia（Algolia搜索）azure（微软Azure搜索）baidu（百度搜索）
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# 顶部菜单（slug请在fontawesome选择）
menu:
  - name: 主页
    slug: fa fa-home
    url: /
  - name: 归档
    slug: fa fa-archive
    url: /archives

# ========================================================================================
# Sidebar
# ========================================================================================

# 侧边栏
# 可选：about（关于）、links（社交链接，请在下面social配置）、categories（分类）、tagcloud（标签页）、qweather（天气功能）
widgets:
  - about
  - links
  - categories
  - tagcloud
  - qweather
  - music

## 侧边音乐播放器
## 使用APlayer+MetingJS
music:
  server: netease  #音乐平台：netease(网易云音乐)，tencent(QQ音乐)，kugou(酷狗音乐)
  type: playlist  #歌曲类型song，playlist，album，search，artist
  id: 7515491376 #（当然可以用我默认的）歌曲ID(song) /播放列表ID(playlist) /专辑ID(album) /搜索关键字(search) /歌手ID(artist)
  fixed: true #吸低模式
  autoplay: true #自动播放
  loop: all #播放器循环播放，值：“all”，one”，“none”
  order: random #播放器播放顺序，值：“list”，“random”
  preload: auto #默认就行
  listfolded: true #指示列表是否应该首先折叠

# 侧边栏社交链接（slug请在fontawesome选择）
social:
- name: github
  slug: fa fa-github
  url: https://github.com/StarWEB890
- name: rss
  slug: fa fa-rss
	url: /atom.xml

# ========================================================================================
# 附加功能
# ========================================================================================

# 评论功能

# Discuss
# https://discuss.js.org/
# （自定义表情请在主题目录下“layout/_thirdparty/emoji.ejs”添加方式请看：https://discuss.js.org/Quick-Start.html#emotmaps）
discuss:
  enable: false # 是否启用 discuss 评论系统
  server_url:  #评论服务端地址
  lang: cn #用于手动设定评论区语言，支持的语言列表 https://discuss.js.org/Quick-Start.html#lang
  ph: 有话想说？ #原名placeholder，评论框占位符，可自定义，默认值与lang有关系

# Twikoo
# https://twikoo.js.org/
twikoo:
  enable: true # 是否启用 Twikoo 评论系统
  envId:  # 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
  region: # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
  lang: zh-CN #用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/js/utils/i18n/index.js

# Gitalk
# https://gitalk.github.io/
# 网上有教程，可以的话按照教程来配置
gitalk:
  enable: false # 是否启用 gitalk 评论系统
  admin:  # 你的 GitHub 用户名
  owner:  # Github 仓库管理者用户名
  repo:  # GitHub 博客的仓库名称
  ClientID:  # 你的ClientID
  ClientSecret: # 你的Client Secret
  labels: #你的issue标签
  distractionFreeMode: true  #无干扰模式

## 萌ICP备案（仅提供萌站长交流！不是真正的中国备案！）
## 申请请到：https://icp.gov.moe/join.php
## 然后把号码粘贴到“code”页面即可（PS:“萌ICP备”不用加上去！）
moeicp:
  enable: false
  code: 

## 不蒜子统计
## https://busuanzi.ibruce.info
busuanzi: true

## canvas
canvas: true

# Less
less:
  compress: true

# Pjax
pjax: true

# 在线聊天（类似在线客服）

#Chatra
chatra: 
  enable: false
  public_key:  #直接复制Public key到此就行

#Daovoice
daovoice: 
  enable: false
  app_id:  #直接复制app_id到此就行

# ========================================================================================
# CDN选择
# ========================================================================================
fontawesome: https://unpkg.com/font-awesome@4.7.0/css/font-awesome.min.css