header:
  home: Home
  archive: Archives
  friend: Friends
  about: About
  say: Said
  comment: Comment
  update: Updates
  travelling: Travelling
  search: Search....

article:
  readmore: Read More

  archive: Archives
  friend: Links
  welcomelinks: Welcome to add friend chain with me!
  friendformat: Friend chain Format

  previous: Prev
  next: Next
  comments: Comments

archive:
  archives: Archives
  previous: Previous
  next: Next

sidebar:
  category: Catrgories
  tagcloud: Tags
  social: Social links
  weather: Weather
  time: Time

footer:
  moeicp: Moeicp Code. %s
  furryicp: Furicp Code. %s
  total: Total %s views.
  visitors: Number of visitors：%s hits
  powered: Powered by %s
  hosted: Hosted by 
  theme: Theme

categories: Category
tags: Tag

copyright:
    author: "Post author: "
    link: "Post link: "
    license_title: "Copyright Notice: "
    left_license_content: "All articles in this blog are licensed under "
    right_license_content: "unless stating additionally."